### ISSUE TITLE
Options in label/value format throws exception

### ISSUE THREAD

**Issue by sylvesterdamgaard** [ryanmitchell/statamic-translation-manager#4]
**Expected behavior:**
A list a labels not translated

**Actual behavior:**
Throws an exception

**Reproduce steps:**
Add a select in a blueprint with the options defined as an array of value/label.
```
options:
  -
    label: 'Some label'
    value: 1
  -
    label: 'Another label'
    value: 2
```

**Version:**
1.0.0

**Issue is found here**
https://github.com/ryanmitchell/statamic-translation-manager/blob/9bcf03aa276a1a730338648578efcd46c564ce81/src/Http/Controllers/BlueprintController.php#L177
